# Generated by Django 5.1.3 on 2024-11-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_password_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passphrase',
            name='passphrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
