# Generated by Django 5.1.3 on 2024-11-16 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_passphrase_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='api.account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.role'),
        ),
    ]
