# Generated by Django 5.1.3 on 2024-11-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_password_account_alter_user_role'),
        ('api', '0004_roles_value'),
    ]

    operations = [
    ]
