# Generated by Django 5.1.3 on 2024-11-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20241116_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='remarks',
            field=models.CharField(max_length=255),
        ),
    ]
