# Generated by Django 5.1.3 on 2024-11-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_analysis_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='url',
            field=models.URLField(default='http://example.com'),
        ),
    ]
