# Generated by Django 5.1.3 on 2024-11-16 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_account_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='url',
            field=models.CharField(default='example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='password',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='api.password'),
        ),
    ]
